POST http://localhost:3000/auth/connexion
Content-Type: application/json

{
    "courriel":"achandelja@gmail.com",
    "motDePasse":"sonofagun1"
}
###
GET http://localhost:3000/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhY2hhbmRlbGphQGdtYWlsLmNvbSIsInJvbGUiOiJWb3lhZ2V1ciIsImlhdCI6MTc4MzEyMjI1NSwiZXhwIjoxNzgzMTI1ODU1fQ.j0ezam55e_l69vpqgM1qoIZnPI3kQfHMkNOLt5KxlmA