@name

POST http://localhost:3000/auth/connexion
Content-Type: application/json

{
    "courriel":"achandelja@gmail.com",
    "motDePasse":"sonofagun1"
}
###
GET http://localhost:3000/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhY2hhbmRlbGphQGdtYWlsLmNvbSIsInJvbGUiOiJWb3lhZ2V1ciIsImlhdCI6MTc4MzEyMjI1NSwiZXhwIjoxNzgzMTI1ODU1fQ.j0ezam55e_l69vpqgM1qoIZnPI3kQfHMkNOLt5KxlmA


###
POST http://localhost:3000/auth/inscription
Content-Type: application/json

{
    "courriel":"gerard_lavoie@gmail.com",
    "motDePasse":"doglover12",
    "nom": "Lavoie",
    "prenom": "Gerard",
}

###
# @name login
POST http://localhost:3000/auth/connexion
Content-Type: application/json

{
    "courriel":"gerard_lavoie@gmail.com",
    "motDePasse":"doglover12"
}

###
POST http://localhost:3000/destinations/importer/Germany
Authorization: Bearer {{login.response.body.token}}


###
GET http://localhost:3000/destinations/liste-pays
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}

### 
PATCH http://localhost:3000/destinations/pays/FRA
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}

{
    "capitale": "Paris",
    "devise": "Euro",
    "langages": "French"
}

###
DELETE http://localhost:3000/destinations/pays/FRA
Authorization: Bearer {{login.response.body.token}}
